title: $ log < tomohiro.me
author: Tomohiro

server: false
auto: false
markdown: rdiscount
pygments: true
permalink: /entries/:title
paginate: 3
category_dir: tags
category_title_prefix: Tag

exclude: ['Gemfile', 'Gemfile.lock', 'README.markdown', 'config.ru']
