title: log.tomohiro.me
author: Tomohiro

server: true
auto: true
markdown: rdiscount
pygments: true
permalink: /entries/:title
paginate: 3
category_dir: tags
category_title_prefix: Tag

exclude: ['README.markdown', 'config.ru']
