#!/usr/bin/env ruby

require 'date'
require 'rubygems'
require 'json'
require 'open-uri'

JEKYLL_ROOT = File::expand_path('..', File.dirname(__FILE__))

def get_input(message)
  print message
  gets.chomp.strip
end

def translate(src, to = 'en')
  base_uri = 'http://ajax.googleapis.com/ajax/services/language'
  begin
    detect = JSON.parse(open("#{base_uri}/detect?v=1.0&q=#{URI.encode(src)}").read)
    from = detect['responseData']['language']
    langpair = "langpair=#{from}%7C#{to}"
    result = JSON.parse(open("#{base_uri}/translate?v=1.0&q=#{URI.encode(src)}&#{langpair}").read)
    result['responseData']['translatedText']
  rescue Exception => e
    "Google: Translation Faild."
  end
end

title     = translate((get_input 'Post Title: ')).downcase.gsub(' ', '-')
extension = 'markdown'
today     = Date.today
path      = JEKYLL_ROOT + "/_draft/#{today}-#{title}.#{extension}"
header    = <<HEADER
---
layout: post
title: #{title}
categories: []
---

{% highlight bash %}
{% endhighlight %}

### References:

HEADER

File.open(path, 'w') { |f| f.write(header) }
system "$EDITOR #{path}"
